services:
    db:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: metrics
        volumes:
            - ./data:/var/lib/postgresql